name: bucky
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0  # Already present, for maps
  provider: ^6.0.0  # Assuming for state management
  cloud_firestore: ^5.0.0  # For Firestore
  firebase_core: ^3.0.0  # For Firebase init
  geolocator: ^12.0.0  # For location services, assuming used elsewhere
  http: ^1.2.2  # Added for Roads API HTTP calls

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true