dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  uuid: ^4.5.1
