name: local_delivery_app
description: A peer-to-peer delivery app prototype
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  geolocator: ^13.0.1
  provider: ^6.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true