name: bucky_osm
description: A P2P delivery app with OpenStreetMap integration
version: 1.0.0
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  cloud_firestore: ^4.3.0
  geofire: ^0.1.0
  flutter_osm_plugin: ^0.14.0  # For OSM map rendering
  http: ^0.13.5  # For OSM API requests
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.2.0 
  http: ^0.13.5  # For OSM API requests


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/osm_data/